name: "vault-test"
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - 'renovate.json'
jobs:
  vault-test:
    runs-on: ubuntu-latest
    if: "! ( ( contains(github.event.pull_request.changed_files, '.github/workflows/*') || contains(github.event.pull_request.changed_files, 'renovate.json') ) && length(github.event.pull_request.changed_files) == length(filter(github.event.pull_request.changed_files, x => x == '.github/workflows/*' || x == 'renovate.json' )) )"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.vault
