name: "Build"
on: [ "pull_request" ]
jobs:
  flake-check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.clippy
  flake-check-sample-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.sample-configs
  flake-check-vault:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.vault
  flake-check-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.file
