name: "Build"
on: [ "pull_request" ]
jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - run: nix shell github:nixos/nixpkgs#renovate --command renovate-config-validator
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.clippy
  sample-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build ./#checks.x86_64-linux.sample-configs
