name: "Build"
on: [ "pull_request" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.6.0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - run: nix --experimental-features "nix-command flakes" build
