name: "Bump-O-Matic"

on:
  schedule:
    - cron: "0 12 * * MON"
  # To allow for manual triggering:
  workflow_dispatch:

jobs:
  bump-o-matic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.6.0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - name: Update dependencies
      run: |
        nix --experimental-features "nix-command flakes" flake update
        nix --experimental-features "nix-command flakes" develop --command cargo update
    - name: Create pull request
      id: pr
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        commit-message: "bump-o-matic: update dependencies"
        branch: bump-o-matic
        delete-branch: true
        title: "Bump-O-Matic: Update dependencies"
        body: "Update dependencies."
